export enum EnvAliases {
  CRYPT_SALT = "CRYPT_SALT",
  JWT_SECRET_KEY = "JWT_SECRET_KEY",
  JWT_SECRET_REFRESH_KEY = "JWT_SECRET_REFRESH_KEY",
  TOKEN_EXPIRE_TIME = "TOKEN_EXPIRE_TIME",
  TOKEN_REFRESH_EXPIRE_TIME = "TOKEN_REFRESH_EXPIRE_TIME",
  LOG_MAX_SIZE = "LOG_MAX_SIZE",
  LOG_LEVEL = "LOG_LEVEL",
}
